### ISSUE TITLE
new connection for every request

### ISSUE THREAD

**Issue by apcode** [russgray/betfairng#1]
Hey Russ,

Thanks for the library, it's well written, succinct and easy to use.
I have one issue with it for my use case. I'm using it for real-time trading and thus calling the api several times per second for over 10 minutes or so. Currently as used, the requests library creates a new https connection for every call which is way too slow. 

Requests has a session object that has the same api but allows reuse of data like headers etc and also to reuse the socket connection which also uses keep-alive.

I haven't tried it yet, but am looking into it now, if you're interested.

**Comment by russgray** [comment]
Thanks for the fix!
